# GitHub actions are pinned to commit hashes to ensure stability and security.

name: Deployability
# Declare default permissions as read only.
permissions: read-all
on:
    pull_request:
        branches:
            - 'main'
    push:
        branches:
            - 'main'

jobs:
  Test-Sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        submodules: recursive
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: 3.12
    - run: python3 -m venv .venv
    - run: .venv/bin/python -m pip install wheel sphinx setuptools
    - run: .venv/bin/python -m pip install -e .[docs]
    - run: .venv/bin/python setup.py apidoc
    - run: .venv/bin/python setup.py build_sphinx -W

  Test-Sanity-Windows:
    permissions:
      id-token: write
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        submodules: recursive
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: 3.12
    - run: python -m venv .venv
    - run: .venv\Scripts\pip install wheel setuptools
    - run: .venv\Scripts\pip install -e .[tests]
    - run: .venv\Scripts\python -m pytest --cov . --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: resurfemg-org/ReSurfEMG


  Test-Sanity-OSX:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        submodules: recursive
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: 3.12
    - run: python3 -m venv .venv
    - run: .venv/bin/python -m pip install wheel
    - run: .venv/bin/python -m pip install -e .[tests]
    - run: .venv/bin/python -m pytest
